Fighter.shape: person

Standing?
Foot position right or left forward

if same leg -> coller tie on side of back foot

if mirrored -> coller tie on side of forward foot -> sweep from outside in
coller tie on side of forward foot -> whizzer
