direction: right                                                               

Client_Apps: {                                                                 
  b: browser                                                                   
}                                                                              
                                                                               
Cloud: {                            
  description: Self managed rented server arch linux single {
    shape: text
    style: {
      font-size: 11
    }
  }

  proxy: proxy                                                                 
}                                                                              
                                                                               
Client_Apps.b -> Cloud.proxy: "http request"                                                                       
